server:
  port: 8200
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8200/euraka
    fetch-registry: false
    register-with-eureka: false


